modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="silver"
version="1.0.0"
displayName="Silver"
credits="https://discord.gg/eCAHRcTYc9"
displayURL="https://discord.gg/eCAHRcTYc9"
authors="The_WereF0X"

[[dependencies.silver]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




